_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b190c324-762f-4392-b826-d4a59e464165
name: Lab03
mail: sergio.espinozacarvajal@ucr.ac.cr
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
